In [20]:
import numpy as np
import pandas as pd
df=pd.read_csv(r'C:\Users\pc\Desktop\hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [21]:
df.shape

(8, 4)

In [23]:
df.describe()

test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [24]:
df.notnull()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       False                   True                        True       True
1       False                   True                        True       True
2        True                   True                        True       True
3        True                   True                        True       True
4        True                   True                        True       True
5        True                   True                        True       True
6        True                  False                        True       True
7        True                   True                        True       True

In [63]:
new={'salary($)':'sal'}
df.rename(columns=new,inplace=True)
df

experience  test_score  interview_score(out of 10)    sal
0        NaN         8.0                           9  50000
1        NaN         8.0                           6  45000
2       five         6.0                           7  60000
3        two        10.0                          10  65000
4      seven         9.0                           6  70000
5      three         7.0                          10  62000
6        ten         NaN                           7  72000
7     eleven         7.0                           8  80000

In [64]:
from word2number import w2n
df2=df.fillna('zero')
df2.experience = df2.experience.apply(w2n.word_to_num)
df2

experience test_score  interview_score(out of 10)    sal
0           0        8.0                           9  50000
1           0        8.0                           6  45000
2           5        6.0                           7  60000
3           2       10.0                          10  65000
4           7        9.0                           6  70000
5           3        7.0                          10  62000
6          10       zero                           7  72000
7          11        7.0                           8  80000

In [70]:
df3=df2.replace(to_replace ='zero', value =0)
df3


experience  test_score  interview_score(out of 10)    sal
0           0         8.0                           9  50000
1           0         8.0                           6  45000
2           5         6.0                           7  60000
3           2        10.0                          10  65000
4           7         9.0                           6  70000
5           3         7.0                          10  62000
6          10         0.0                           7  72000
7          11         7.0                           8  80000

In [71]:
df3.corr()

experience  test_score  \
experience                    1.000000   -0.552513   
test_score                   -0.552513    1.000000   
interview_score(out of 10)   -0.290480    0.253622   
sal                           0.908017   -0.289677   

                            interview_score(out of 10)       sal  
experience                                   -0.290480  0.908017  
test_score                                    0.253622 -0.289677  
interview_score(out of 10)                    1.000000  0.037820  
sal                                           0.037820  1.000000

In [72]:
from sklearn import linear_model
# print(df3)
reg = linear_model.LinearRegression()
reg.fit(df3.drop('sal',axis='columns'),df3.sal)

   experience  test_score  interview_score(out of 10)    sal
0           0         8.0                           9  50000
1           0         8.0                           6  45000
2           5         6.0                           7  60000
3           2        10.0                          10  65000
4           7         9.0                           6  70000
5           3         7.0                          10  62000
6          10         0.0                           7  72000
7          11         7.0                           8  80000


LinearRegression()

In [73]:
reg.coef_

array([3077.8642085 ,  999.7856246 , 2118.48834717])

In [74]:
reg.intercept_

24823.523106605797

In [75]:
reg.predict([[2,9,6]])

C:\Users\pc\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52688.25222797])

In [76]:
3077.8642085*2 + 999.7856246*9 + 2118.48834717*6 + 24823.523106605797

52688.2522280258

In [77]:
reg.predict([[12,10,10]])

C:\Users\pc\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92940.63332619])

In [78]:
3077.8642085*12 + 999.7856246*10 + 2118.48834717*10 + 24823.523106605797

92940.6333263058